# Generated by Django 3.2.25 on 2025-12-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('user', 'title')},
        ),
    ]
